version: '2'

services:
  kmactf:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:kmactf@db/kmactf
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/KMActf
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - .data/KMActf/logs:/var/log/KMActf
      - .data/KMActf/uploads:/var/uploads
      - .:/opt/KMActf:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=kmactf
      - MYSQL_USER=kmactf
      - MYSQL_PASSWORD=kmactf
      - MYSQL_DATABASE=kmactf
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
